version: '3'
services:
    hotelsearch:
        build: ./hotelsearch
        volumes:
            - ./hotelsearch:/var/www/html
        image: php:7.0-apache
        ports:
            - 5000:80
    imageserver:
        build: ./imageserver
        volumes:
            - ./imageserver:/var/www/html
        image: php:7.0-apache
        ports:
            - 5001:80
    website:
        build: ./website
        volumes:
            - ./website:/var/www/html
        image: php:7.0-apache
        ports:
            - 81:80
    screenshot:
        build: ./screenshot
        container_name: screenshot
        ports:
            - 8888:8888
