version: '3'
services:
    hotelsearch:
        #build: ./hotelsearch
        volumes:
            - ./hotelsearch:/var/www/html
        image: php:7.0-apache
        ports:
            - 5000:80
    imageserver:
        #build: ./imageserver
        volumes:
            - ./imageserver:/var/www/html
        image: php:7.0-apache
        ports:
            - 5001:80
    website:
        build:
            context: ./website
            dockerfile: Dockerfile
        volumes:
            - ./website/src/webcoding:/var/www/html
        ports:
            - 80:80
        command:
            - php artisan key:generate
            - php artisan config:clear
            - php artisan config:cache
    screenshot:
        build:
            context: ./screenshot
            dockerfile: Dockerfile
        security_opt:
            - seccomp:unconfined
        ports:
            - 5002:80
    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - ./website/src/webcoding:/app
